### ISSUE TITLE
Math redone

### ISSUE THREAD

**Issue by larry0x** [left-curve/grug#22]
In CosmWasm there are the types `Uint{64,128,256,512}` but they are basically the same file copy-pasted. Same situation with `Int64/128/256/512`, `Decimal128/512`, and `SignedDecimal128/512`. We want to avoid the duplicate code.

Also, CosmWasm uses [bnum](https://crates.io/crates/bnum) underneath which isn't a particularly popular library (only about 500k all time downloads).

Ideas:

- Switch from bnum to [crypto-bigint](https://crates.io/crates/crypto-bigint), which is part of RustCrypto, a high quality project, and is the basis of crypto libraries such as [elliptic-curve](https://crates.io/crates/elliptic-curve/0.13.8).

- Create a single `Uint<T>` struct to represent all unsigned integer types:

  ```rust
  type Uint64 = Uint<u64>;
  type Uint128 = Uint<u128>;
  type Uint256 = Uint<crypto_bigint::U256>;
  type Uint512 = Uint<crypto_bigint::U512>;
  ```

- Create a `Decimal<T>` type to represent all fixed-point number types:

  ```rust
  type Decimal128 = Decimal<Uint128>;
  type Decimal256 = Decimal<Uint256>;
  ```

- Create a `Signed<T>` type to represent all signed number types:

  ```rust
  type Int128 = Signed<Uint128>;
  type SignedDecimal128 = Signed<Decimal128>;
  ```

**Comment by larry0x** [comment]
Note: when importing crypto-bigint, make sure to disable default features, otherwise randomness operators are included

```toml
[dependencies]
crypto-bigint = { version = "0.5.5", default-features = false, features = ["serde", "borsh"] };
```

**Comment by Rhaki** [comment]
Based on the current design:
- Change from `bnum `to `crypt-bigint`;
- Remove current `Signed `and `Int `types created with macros;
- Create a new struct `Signed<T>`;
- Impls matsh ops for `Signed<T>`
- Define new `Signed `(`Decimals `and `Int`) with new macros;

**Comment by larry0x** [comment]
Completed
