### ISSUE TITLE
Math - square root methods

### ISSUE THREAD

**Issue by larry0x** [left-curve/grug#23]
We need to figure out whether the square root method we implement for `Uint` and `Decimal` etc. are _rounded down_ or _rounded to nearest_, and add a comment to specify this (or maybe even rename the function to make it clear). This behavior can greatly impact DeFi protocols.

**Comment by dzmitry-lahoda** [comment]
Good, so imho DeFi never needs `Decimal`.  Any kind of `Decimal` is misleading leaking abstraction.

**Comment by larry0x** [comment]
Answer: it's rounded towards zero (floored).
