### ISSUE TITLE
`Coins::new_one` doesn't ensure amount is non-zero

### ISSUE THREAD

**Issue by larry0x** [left-curve/grug#44]

**Comment by dzmitry-lahoda** [comment]
`new_one` receives `NonZero`, which panics in case of zero amount on main. it seems was fixed?

**Comment by Rhaki** [comment]
This has been fixed with [this](https://github.com/left-curve/grug/commit/7f2a3c4daa1f6f578ab65da4f46630f0c6201bde). Can be closed
