### ISSUE TITLE
IndexSet: is it worth?

### ISSUE THREAD

**Issue by Rhaki** [left-curve/grug#53]
The implementation of `IndexSet` is a forced adaptation compared to an `IndexMap`. For proper functionality, we still need to save the various indices in the `primary` map, as they are necessary when removing a key, and reading the various secondary indices linked to the main key for their removal.

The only differences are:

- On `UniqueIndex`,  instead of having a map like `idx_map: Map<IK, T>`, we have `idx_map: Map<IK, PK>`.

- On `MultiIndex`, it is no longer necessary to have the reference to the `primary_map`, and in the `IndexPrefixSet` (counterpart to `IndexPrefixMap`) the methods `values_raw` and `values` are removed.

To be discussed if the implementation is worth it. The code is actually ready under [this](https://github.com/left-curve/grug/tree/index-set) branch.

**Comment by larry0x** [comment]
Not planned
