### ISSUE TITLE
Better cronjobs

### ISSUE THREAD

**Issue by larry0x** [left-curve/grug#56]
Right now we implement cronjobs using "begin/end blockers", similarly as done in Cosmos SDK.

The drawback of this is that every begin/end blocker contract is called every block, even though a lot of tasks only need to be called much less frequently than that, e.g. once every 10 minutes or so.

We can improve this like this: first, replace `{begin,end}_blockers` in the chain-level `Config` with:

```rust
struct Config {
    /// Addresses of contracts to be called,
    /// and how often each of them is to be called.
    pub cronjobs: BTreeMap<Addr, Duration>,
}
```

The chain tracks cronjobs in the following data structure:

```rust
const CRONJOBS: Set<(Timestamp, Addr)>;
```

Where this `Timestamp` is the next time this cronjob is to be performed.

At the beginning of each block, the chain retrieves a list of cronjobs, of which the scheduled execution time is less or equal than the current block time; execute them one by one; then, update the next execute time:

```rust
let jobs = CRONJOBS
    .range(&storage, None, Some(current_block_time), Order::Ascending)
    .collect::<StdResult<Vec<_>>>()?;

for (old_time, address) in jobs {
    // Call the contract
    // ...

    let interval = config.cronjobs[&address];
    let new_time = current_block_time + interval;

    CRONJOBS.remove(&mut storage, old_time);
    CRONJOBS.save(&mut storage, new_time, &address)?;
}
```

**Comment by Rhaki** [comment]
I would suggest using duration instead of timestamp. This is because if there is a need to be called every block, the timestamp may not be accurate. Then create two maps, one with block height and one with timestamp

**Comment by Rhaki** [comment]
I also think we need to use a `Set<expiration, address>` because two contract could have the same expiration. we need only to iterate over them, so set with prefix for iter is working

**Comment by larry0x** [comment]
> if there is a need to be called every block

Set the time interval to zero then it should work

> need to use a Set<(expiration, address)> because two contract could have the same expiration

Right
