### ISSUE TITLE
Charge gas fee if `before_tx` fails

### ISSUE THREAD

**Issue by larry0x** [left-curve/grug#71]
The current way `grug_app::process_tx` works, if the `before_tx` call fails, the transaction is aborted and no state change is committed.

However, we still need to charge gas fee in this case, otherwise an attacker can spam failed transactions at no cost.

**Comment by Rhaki** [comment]
In reality we actually have the same problem with msgs and after_tx. If one of these fails, process tx return an error. We could wrap before_tx, msgs and after_tx in a closure or another function. Call the taxman regardless the result and in case of success commit the storage.

**Comment by larry0x** [comment]
> In reality we actually have the same problem with msgs and after_tx. If one of these fails, process tx return an error. We could wrap before_tx, msgs and after_tx in a closure or another function. Call the taxman regardless the result and in case of success commit the storage.

Yeah

**Comment by larry0x** [comment]
Completed in #83
