### ISSUE TITLE
Better Credential for std Account

### ISSUE THREAD

**Issue by Rhaki** [left-curve/grug#75]
It credential field of a tx using the default account, instead of having the signature in binary, a serialized struct could be used where there are both the signature field and other fields, such as the sequence. True, it is not necessary to have the sequence as a parameter, however if the signature verification fails, is possible to return a dedicated error if the sequence does not match. Currently, however, is not possible to know if the verification fails for the sequence or something else. Furthermore, having the sequence in the signature allow in the check tx to verify whether the signature is correct using a sequence different from the one saved in the state, thus allowing the possibility of verifying a signature and accepting multiple txes in the mempool from the same sender.

**Comment by larry0x** [comment]
Completed by #85
